In [24]:
import torch

# https://wikidocs.net/52460

# Tensor 1D
print("Tensor 1D")
t1d = torch.FloatTensor([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0])

print(f"t value: {t1d}")
print(f"rank: {t1d.dim()}")
print(f"shape: {t1d.shape}")
print(f"size: {t1d.size()}")

print(f"Get tensor value for index 3: {t1d[3]}")
print(f"Get tensor value with slice: {t1d[2:5]}")
print(f"Get tensor value with slice: {t1d[:3]}")

# Tensor 2D
print("Tensor 2D")
t2d = torch.FloatTensor([
                        [0.0, 1.0, 2.0],
                        [3.0, 4.0, 5.0],
                        [6.0, 7.0, 8.0],
                        [9.0, 10.0, 11.0]
                        ])

print(f"t value: {t2d}")
print(f"rank: {t2d.dim()}")
print(f"shape: {t2d.shape}")
print(f"size: {t2d.size()}")

print(f"Get tensor value for index 3: {t2d[3]}")
print(f"Get tensor value for index 3, 2: {t2d[3,2]}")
print(f"Get tensor value with slice: {t2d[2:3]}")
print(f"Get tensor value with slice: {t2d[:,1]}")
print(f"Get tensor value with slice: {t2d[:,:-1]}")

# Broadcasting for Tensor
print("Broadcasting")

# If each Tensor size is same, there have no broadcasting.
m1 = torch.FloatTensor([1.0, 2.0]) # Tensor 1D
m2 = torch.FloatTensor([4.0, 3.0]) # Tensor 1D
print(m1 + m2)

m3 = torch.FloatTensor([1.0, 2.0]) # Tensor 1D
m4 = torch.FloatTensor([3.0]) # Tensor 1D, It will be broadcasting as like [3.0] -> [3.0, 3.0]
print(m3 + m4)

m5 = torch.FloatTensor([1.0, 2.0]) # Tensor 1D, It will be broadcasting as like below
#m5 = torch.FloatTensor(
                      #[[1.0, 2.0],
                      # [1.0, 2.0]]
                      #) # Tensor 2D
m6 = torch.FloatTensor(
                      [[3.0, 4.0],
                       [5.0, 6.0]]
                      ) # Tensor 2D
print(m5 + m6)

# Matrix Multiplication
print("Matrix Multiplication")
print('Shape of m5: ', m5.shape)
print('Shape of m6: ', m6.shape)
print(m6.matmul(m5))

# Multiplication
print("Multiplication")
print(m6.mul(m5)) # With broadcasting
print(m6 * m5) # With broadcasting

# Mean
print("Mean")
print(t1d.mean())
print(m6.mean())
print(m6.mean(dim=0))
print(m6.mean(dim=1))

# Sum
print("Sum")
print(m6.sum())
print(m6.sum(dim=0))
print(m6.sum(dim=1))
print(m6.sum(dim=-1))

# Max
print("Max")
print(m6.max())
print(m6.max(dim=0))
print('Max: ', m6.max(dim=0)[0])
print('Argmax: ', m6.max(dim=0)[1])
print(m6.max(dim=1))
print(m6.max(dim=-1))

Tensor 1D
t value: tensor([0., 1., 2., 3., 4., 5., 6.])
rank: 1
shape: torch.Size([7])
size: torch.Size([7])
Get tensor value for index 3: 3.0
Get tensor value with slice: tensor([2., 3., 4.])
Get tensor value with slice: tensor([0., 1., 2.])
Tensor 2D
t value: tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
rank: 2
shape: torch.Size([4, 3])
size: torch.Size([4, 3])
Get tensor value for index 3: tensor([ 9., 10., 11.])
Get tensor value for index 3, 2: 11.0
Get tensor value with slice: tensor([[6., 7., 8.]])
Get tensor value with slice: tensor([ 1.,  4.,  7., 10.])
Get tensor value with slice: tensor([[ 0.,  1.],
        [ 3.,  4.],
        [ 6.,  7.],
        [ 9., 10.]])
Broadcasting
tensor([5., 5.])
tensor([4., 5.])
tensor([[4., 6.],
        [6., 8.]])
Matrix Multiplication
Shape of m5:  torch.Size([2])
Shape of m6:  torch.Size([2, 2])
tensor([11., 17.])
Multiplication
tensor([[ 3.,  8.],
        [ 5., 12.]])
tensor([[ 3.,  8.],
  